services:
  # Frontend service
  - type: web
    name: wiktoriabeutybrows-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://wiktoriabeutybrows-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend service
  - type: web
    name: wiktoriabeutybrows-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    healthCheckPath: ./
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wiktoriabeutybrows-db
          property: connectionString
      - key: DB_TYPE
        value: postgres
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production

# Render.com nie obsługuje MySQL w Blueprint, używamy PostgreSQL
databases:
  - name: wiktoriabeutybrows-db
    plan: free